name: MLOps CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install dvc[s3]
          pip install -r requirements.txt

      - name: Pull Data and Model from S3
        env:
          AWS_ACCESS_KEY_ID: \${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1 # Change this to your bucket's region if different
        run: |
          dvc pull

      - name: Build Docker Image
        run: |
          docker build -t wine-prediction-app .

      - name: Test Docker Container
        run: |
          docker run -d -p 5000:5000 --name test-container wine-prediction-app
          sleep 10
          curl -X POST http://127.0.0.1:5000/predict \\
               -H "Content-Type: application/json" \\
               -d '[{"fixed_acidity": 7.4, "volatile_acidity": 0.7, "citric_acid": 0.0, "residual_sugar": 1.9}]'
